# Generated by Django 5.2.7 on 2025-11-07 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_district_state_constituency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BulkUploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('validation_errors', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_upload_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Upload Job',
                'verbose_name_plural': 'Bulk Upload Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_data', models.JSONField()),
                ('error_message', models.TextField()),
                ('error_field', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='api.bulkuploadjob')),
            ],
            options={
                'verbose_name': 'Bulk Upload Error',
                'verbose_name_plural': 'Bulk Upload Errors',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkuploadjob',
            index=models.Index(fields=['created_by', '-created_at'], name='api_bulkupl_created_629334_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploadjob',
            index=models.Index(fields=['status'], name='api_bulkupl_status_d9fe19_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploadjob',
            index=models.Index(fields=['job_id'], name='api_bulkupl_job_id_52ef44_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploaderror',
            index=models.Index(fields=['job', 'row_number'], name='api_bulkupl_job_id_44bb1f_idx'),
        ),
    ]
