# Generated by Django 5.2.7 on 2025-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_must_change_password_bulkuploadjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='constituency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
