# Generated by Django 5.2.7 on 2025-11-08 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_city_userprofile_constituency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingBooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(help_text="Official booth number (e.g., '001', '002A')", max_length=20)),
                ('name', models.CharField(help_text='Polling booth name/location', max_length=300)),
                ('building_name', models.CharField(blank=True, help_text='School/building name', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, help_text='Locality/area name', max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('total_voters', models.IntegerField(default=0, help_text='Total registered voters')),
                ('male_voters', models.IntegerField(default=0)),
                ('female_voters', models.IntegerField(default=0)),
                ('other_voters', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional booth information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_booths', to='api.constituency')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_booths', to='api.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_booths', to='api.state')),
            ],
            options={
                'verbose_name': 'Polling Booth',
                'verbose_name_plural': 'Polling Booths',
                'ordering': ['constituency', 'booth_number'],
                'indexes': [models.Index(fields=['state', 'district'], name='api_polling_state_i_0729bf_idx'), models.Index(fields=['constituency'], name='api_polling_constit_eb8025_idx'), models.Index(fields=['booth_number'], name='api_polling_booth_n_33d558_idx'), models.Index(fields=['is_active'], name='api_polling_is_acti_509cf6_idx')],
                'unique_together': {('constituency', 'booth_number')},
            },
        ),
    ]
