# Generated by Django 5.2.7 on 2025-11-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_security_and_performance'),
        ('api', '0007_workstream2_core_models'),
        ('api', '0009_pollingbooth'),
    ]

    operations = [
    ]
