# Generated by Django 5.2.7 on 2025-11-09 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20251109_0533'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='Hashed backup code', max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '2FA Backup Code',
                'verbose_name_plural': '2FA Backup Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='voter',
            new_name='api_voter_voter_i_06dc6b_idx',
            old_name='api_voter_voter_i_idx',
        ),
        migrations.RenameIndex(
            model_name='voter',
            new_name='api_voter_constit_b8d453_idx',
            old_name='api_voter_const_ward_idx',
        ),
        migrations.RenameIndex(
            model_name='voter',
            new_name='api_voter_party_a_dd4424_idx',
            old_name='api_voter_party_idx',
        ),
        migrations.RenameIndex(
            model_name='voter',
            new_name='api_voter_sentime_e99cf7_idx',
            old_name='api_voter_sentiment_idx',
        ),
        migrations.RenameIndex(
            model_name='voter',
            new_name='api_voter_phone_2a7877_idx',
            old_name='api_voter_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='voter',
            new_name='api_voter_is_acti_8d4be4_idx',
            old_name='api_voter_active_idx',
        ),
        migrations.RenameIndex(
            model_name='voter',
            new_name='api_voter_created_c4c627_idx',
            old_name='api_voter_created_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Branding colors, email templates, etc.'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['target_role'], name='api_alert_target__b87eed_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority'], name='api_alert_priorit_5d8732_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read'], name='api_alert_is_read_26b5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='api_alert_created_6e8842_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='api_campaig_status_2812a2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='api_campaig_campaig_b34021_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='api_campaig_start_d_eb2cff_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_manager'], name='api_campaig_campaig_2cd5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='api_event_event_t_18ed61_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='api_event_status_d5f5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='api_event_start_d_e1b2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['constituency'], name='api_event_constit_a6d639_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type'], name='api_expense_expense_839042_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='api_expense_status_c30168_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['campaign'], name='api_expense_campaig_2c256e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['event'], name='api_expense_event_i_0d03f8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-created_at'], name='api_expense_created_d5f834_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['platform', '-posted_at'], name='api_socialm_platfor_800101_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['campaign'], name='api_socialm_campaig_5e98df_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['is_published'], name='api_socialm_is_publ_0312a4_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['-posted_at'], name='api_socialm_posted__b0943a_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerprofile',
            index=models.Index(fields=['volunteer_id'], name='api_volunte_volunte_65a6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerprofile',
            index=models.Index(fields=['assigned_constituency'], name='api_volunte_assigne_db289f_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerprofile',
            index=models.Index(fields=['is_active'], name='api_volunte_is_acti_698f88_idx'),
        ),
        migrations.AddIndex(
            model_name='voterinteraction',
            index=models.Index(fields=['voter', '-interaction_date'], name='api_voterin_voter_i_6091f4_idx'),
        ),
        migrations.AddIndex(
            model_name='voterinteraction',
            index=models.Index(fields=['contacted_by'], name='api_voterin_contact_2630c7_idx'),
        ),
        migrations.AddIndex(
            model_name='voterinteraction',
            index=models.Index(fields=['interaction_type'], name='api_voterin_interac_1651dc_idx'),
        ),
        migrations.AddIndex(
            model_name='voterinteraction',
            index=models.Index(fields=['sentiment'], name='api_voterin_sentime_fdc2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='voterinteraction',
            index=models.Index(fields=['follow_up_required'], name='api_voterin_follow__3b0505_idx'),
        ),
        migrations.AddField(
            model_name='twofactorbackupcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twofactor_backup_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='twofactorbackupcode',
            index=models.Index(fields=['user', 'is_used'], name='api_twofact_user_id_033b6f_idx'),
        ),
    ]
