# Generated by Django 5.2.7 on 2025-11-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_botconfiguration_whatsappconversation_voterprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supabase_uid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Supabase Auth user ID (UUID) for hybrid authentication', null=True, unique=True),
        ),
    ]
