# Generated by Django 5.2.7 on 2025-11-10 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_botconfiguration_whatsappconversation_voterprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('source', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('article_text', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(choices=[('ta', 'Tamil'), ('en', 'English'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('word_count', models.IntegerField(default=0)),
                ('tvk_sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], db_index=True, default='neutral', max_length=20)),
                ('tvk_sentiment_score', models.DecimalField(decimal_places=2, default=0.5, help_text='0.00 (very negative) to 1.00 (very positive)', max_digits=3)),
                ('vijay_mentions', models.IntegerField(default=0)),
                ('tvk_mentions', models.IntegerField(default=0)),
                ('dmk_mentions', models.IntegerField(default=0)),
                ('opposition_mentions', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('key_topics', models.JSONField(blank=True, default=list, help_text="['jobs', 'neet', 'water_crisis']")),
                ('sentiment_reasoning', models.TextField(blank=True, help_text='LLM explanation for sentiment classification', null=True)),
                ('entities_mentioned', models.JSONField(blank=True, default=list, help_text="['Vijay', 'Stalin', 'BJP', 'Chennai']")),
                ('is_relevant', models.BooleanField(default=True, help_text='Is this article relevant to TN politics/TVK?')),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('election', 'Election'), ('policy', 'Policy'), ('governance', 'Governance'), ('social_issue', 'Social Issue'), ('economy', 'Economy'), ('other', 'Other')], default='politics', max_length=50)),
                ('ai_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('processing_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'db_table': 'news_articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_articl_publish_d1e015_idx'), models.Index(fields=['source', '-published_at'], name='news_articl_source_6b9a79_idx'), models.Index(fields=['tvk_sentiment', '-published_at'], name='news_articl_tvk_sen_60f7db_idx'), models.Index(fields=['language', '-published_at'], name='news_articl_languag_81e290_idx')],
            },
        ),
    ]
