-- Social Media Posts Seed Data - SAMPLE
-- Generated: 2024-11-09 12:00:00
-- Total posts: 20,000 (This is a sample showing first 10 posts)
--
-- This file shows the structure. The actual seed file will contain all 20,000 posts.
-- Generated by: python manage.py generate_social_posts --generate-sql

-- ============================================================================
-- TABLE SCHEMA (for reference)
-- ============================================================================
/*
CREATE TABLE IF NOT EXISTS social_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    platform VARCHAR(20) NOT NULL,
    post_content TEXT NOT NULL,
    post_url TEXT,
    post_id VARCHAR(200),
    posted_at TIMESTAMP NOT NULL,
    reach INTEGER DEFAULT 0,
    impressions INTEGER DEFAULT 0,
    engagement_count INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    shares INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    sentiment_score DECIMAL(4,2),
    campaign_id UUID,
    is_published BOOLEAN DEFAULT false,
    is_promoted BOOLEAN DEFAULT false,
    hashtags TEXT[],
    mentions TEXT[],
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
*/

-- ============================================================================
-- DROP EXISTING DATA (optional - uncomment to clear existing posts)
-- ============================================================================
-- TRUNCATE TABLE social_posts CASCADE;

-- ============================================================================
-- INSERT SAMPLE POSTS
-- ============================================================================

INSERT INTO social_posts (
    id, platform, post_content, post_url, post_id, posted_at,
    reach, impressions, engagement_count, likes, shares, comments_count,
    sentiment_score, campaign_id, is_published, is_promoted, hashtags, mentions,
    created_at, updated_at
) VALUES

-- Post 1: Twitter - Water Crisis (High Engagement)
(
    'a1b2c3d4-e5f6-4a5b-8c7d-9e0f1a2b3c4d',
    'twitter',
    'Water shortage in Chennai! When will this crisis end? #TNWaterCrisis #SaveTamilNadu',
    'https://twitter.com/user/status/1234567890123456789',
    '1234567890123456789',
    '2024-11-27 18:45:32',
    12500,
    25000,
    850,
    720,
    95,
    35,
    0.32,
    NULL,
    true,
    false,
    ARRAY['#TNWaterCrisis', '#SaveTamilNadu', '#WaterScarcity'],
    ARRAY['@TNGovt', '@ChennaiMetroWater'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
),

-- Post 2: Facebook - TVK Support (Viral)
(
    'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
    'facebook',
    'Vijay''s speech on jobs resonated with youth! #TVK #VijayForTN #TamilNaduFuture',
    'https://facebook.com/post/234567890123456',
    '234567890123456',
    '2024-11-26 19:15:20',
    125000,
    250000,
    15420,
    12500,
    2100,
    820,
    0.85,
    NULL,
    true,
    true,
    ARRAY['#TVK', '#VijayForTN', '#TamilNaduFuture', '#CleanPolitics'],
    ARRAY['@TVKOfficial', '@ActorVijay'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
),

-- Post 3: Instagram - Development (Medium Engagement)
(
    'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f',
    'instagram',
    'New infrastructure projects announced for Coimbatore district #TNDevelopment #Progress',
    'https://instagram.com/p/CxYz123AbCd/',
    'CxYz123AbCd',
    '2024-11-28 13:30:15',
    3200,
    6400,
    285,
    245,
    28,
    12,
    0.78,
    NULL,
    true,
    false,
    ARRAY['#TNDevelopment', '#Progress', '#Coimbatore'],
    ARRAY['@TNGovt'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
),

-- Post 4: Twitter - NEET Protest (High Engagement)
(
    'd4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a',
    'twitter',
    'NEET destroyed dreams of rural students. When will TN get exemption? #NEETHurts #StopNEET',
    'https://twitter.com/user/status/9876543210987654321',
    '9876543210987654321',
    '2024-11-25 20:22:45',
    8500,
    17000,
    620,
    485,
    95,
    40,
    0.38,
    NULL,
    true,
    false,
    ARRAY['#NEETHurts', '#StopNEET', '#TNStudents', '#AbolishNEET'],
    ARRAY['@TNGovt', '@EducationMinTN'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
),

-- Post 5: Facebook - Cauvery Water (Medium Engagement)
(
    'e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b',
    'facebook',
    'Karnataka not releasing Cauvery water. Delta farmers suffering! #CauveryWater #SaveDeltaFarmers',
    'https://facebook.com/post/345678901234567',
    '345678901234567',
    '2024-11-24 12:10:30',
    4200,
    8400,
    315,
    265,
    35,
    15,
    0.35,
    NULL,
    true,
    false,
    ARRAY['#CauveryWater', '#SaveDeltaFarmers', '#CauveryDispute', '#FarmersFirst'],
    ARRAY['@TNGovt', '@KarnatakaGovt'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
),

-- Post 6: Twitter - Fishermen Rights (Low Engagement)
(
    'f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c',
    'twitter',
    '530 TN fishermen arrested by SL Navy this year. Enough is enough! #TNFishermen #SriLanka',
    'https://twitter.com/user/status/5678901234567890123',
    '5678901234567890123',
    '2024-11-29 07:35:12',
    425,
    850,
    38,
    28,
    7,
    3,
    0.42,
    NULL,
    true,
    false,
    ARRAY['#TNFishermen', '#SriLanka', '#FishermenRights'],
    ARRAY['@TNGovt', '@MEAIndia'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
),

-- Post 7: Instagram - TVK Rally (Medium Engagement)
(
    'a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d',
    'instagram',
    'Finally a leader who speaks for common people! @TVKOfficial #TVKVision2026 #NewPolitics',
    'https://instagram.com/p/DefGhi456XyZ/',
    'DefGhi456XyZ',
    '2024-11-27 19:50:25',
    5600,
    11200,
    420,
    365,
    38,
    17,
    0.82,
    NULL,
    true,
    false,
    ARRAY['#TVKVision2026', '#NewPolitics', '#TVK'],
    ARRAY['@TVKOfficial'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
),

-- Post 8: YouTube - TVK Speech (Viral)
(
    'b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e',
    'youtube',
    'Vijay addresses NEET issue head-on. This is the leadership we need! #StopNEET #TVK',
    'https://youtube.com/watch?v=dQw4w9WgXcQ',
    'dQw4w9WgXcQ',
    '2024-11-26 20:15:40',
    185000,
    370000,
    28500,
    24200,
    3100,
    1200,
    0.88,
    NULL,
    true,
    true,
    ARRAY['#StopNEET', '#TVK', '#VijayForTN'],
    ARRAY['@TVKOfficial', '@ActorVijay'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
),

-- Post 9: Twitter - Healthcare Development (Low Engagement)
(
    'c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f',
    'twitter',
    'Healthcare expansion in rural areas. Good move! #TNHealthcare #RuralDevelopment',
    'https://twitter.com/user/status/6789012345678901234',
    '6789012345678901234',
    '2024-11-23 08:20:18',
    280,
    560,
    22,
    18,
    3,
    1,
    0.72,
    NULL,
    true,
    false,
    ARRAY['#TNHealthcare', '#RuralDevelopment', '#TNDevelopment'],
    ARRAY['@TNGovt'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
),

-- Post 10: Facebook - Water Crisis Madurai (Medium Engagement)
(
    'd0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a',
    'facebook',
    'Madurai water levels dropped 10 meters. Government sleeping? #WaterCrisis #TamilNadu',
    'https://facebook.com/post/456789012345678',
    '456789012345678',
    '2024-11-28 18:40:55',
    3800,
    7600,
    295,
    250,
    32,
    13,
    0.28,
    NULL,
    true,
    false,
    ARRAY['#WaterCrisis', '#TamilNadu', '#Madurai', '#TNWaterCrisis'],
    ARRAY['@TNGovt', '@CMOTamilNadu'],
    '2024-11-09 12:00:00',
    '2024-11-09 12:00:00'
);

-- ============================================================================
-- POST-INSERT OPERATIONS
-- ============================================================================

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_social_posts_platform ON social_posts(platform);
CREATE INDEX IF NOT EXISTS idx_social_posts_posted_at ON social_posts(posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_social_posts_campaign ON social_posts(campaign_id);
CREATE INDEX IF NOT EXISTS idx_social_posts_sentiment ON social_posts(sentiment_score);
CREATE INDEX IF NOT EXISTS idx_social_posts_engagement ON social_posts(engagement_count DESC);
CREATE INDEX IF NOT EXISTS idx_social_posts_is_published ON social_posts(is_published);
CREATE INDEX IF NOT EXISTS idx_social_posts_is_promoted ON social_posts(is_promoted);

-- GIN indexes for array columns (hashtags, mentions)
CREATE INDEX IF NOT EXISTS idx_social_posts_hashtags ON social_posts USING GIN(hashtags);
CREATE INDEX IF NOT EXISTS idx_social_posts_mentions ON social_posts USING GIN(mentions);

-- Full-text search index on post content
CREATE INDEX IF NOT EXISTS idx_social_posts_content_search ON social_posts USING GIN(to_tsvector('english', post_content));

-- Analyze table for query optimization
ANALYZE social_posts;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Total posts by platform
SELECT platform, COUNT(*) as post_count,
       ROUND(AVG(engagement_count), 2) as avg_engagement,
       ROUND(AVG(sentiment_score), 2) as avg_sentiment
FROM social_posts
GROUP BY platform
ORDER BY post_count DESC;

-- Viral posts (high engagement)
SELECT platform, post_content, likes, shares, comments_count, engagement_count
FROM social_posts
WHERE engagement_count > 10000
ORDER BY engagement_count DESC;

-- Sentiment breakdown
SELECT
    CASE
        WHEN sentiment_score >= 0.6 THEN 'Positive'
        WHEN sentiment_score <= 0.4 THEN 'Negative'
        ELSE 'Neutral'
    END as sentiment,
    COUNT(*) as count,
    ROUND(AVG(engagement_count), 2) as avg_engagement
FROM social_posts
GROUP BY sentiment
ORDER BY count DESC;

-- Top hashtags
SELECT hashtag, COUNT(*) as frequency
FROM social_posts, unnest(hashtags) as hashtag
GROUP BY hashtag
ORDER BY frequency DESC
LIMIT 20;

-- Posts by date
SELECT DATE(posted_at) as post_date,
       COUNT(*) as posts,
       SUM(engagement_count) as total_engagement
FROM social_posts
GROUP BY DATE(posted_at)
ORDER BY post_date;

-- ============================================================================
-- SAMPLE COMPLETED
-- ============================================================================
-- This sample shows 10 posts.
-- The full seed file will contain all 20,000 posts with similar structure.
--
-- To generate the full file:
-- python manage.py generate_social_posts --generate-sql
--
-- Platform breakdown:
--   Twitter:   10,000 posts (50%)
--   Facebook:   6,000 posts (30%)
--   Instagram:  3,000 posts (15%)
--   YouTube:      600 posts (3%)
--   WhatsApp:     400 posts (2%)
--
-- Engagement tiers:
--   Viral:      1,000 posts (5%)
--   High:       3,000 posts (15%)
--   Medium:     8,000 posts (40%)
--   Low:        8,000 posts (40%)
-- ============================================================================
