"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY MUST be set via environment variable
if 'SECRET_KEY' not in os.environ:
    import warnings
    warnings.warn(
        'SECRET_KEY not found in environment. Using insecure default for development only. '
        'Set SECRET_KEY environment variable in production!',
        RuntimeWarning
    )
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-development-only-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False for safety - set DEBUG=True explicitly for development
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS with Railway domain hardcoded as fallback
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Always add Railway domain (works even if env vars aren't loaded)
ALLOWED_HOSTS.extend([
    'pulseofpeople-production.up.railway.app',
    '.railway.app',  # Allow all Railway domains
])

# Production domains
if not DEBUG:
    ALLOWED_HOSTS.extend([
        'pulseofpeople.com',
        'www.pulseofpeople.com',
        'api.pulseofpeople.com',
    ])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',

    # Local apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'api.middleware.security_headers.SecurityHeadersMiddleware',  # Security headers
    'api.middleware.security_headers.RequestSizeMiddleware',  # Request size limit
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.role_auth_middleware.RoleAuthMiddleware',  # Custom role middleware
    'api.middleware.role_auth_middleware.RequestLoggingMiddleware',  # Request logging
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Response compression
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Configuration
# Temporarily using SQLite for local development
# Switch back to PostgreSQL once Supabase connection is resolved

USE_SQLITE = os.environ.get('USE_SQLITE', 'True') == 'True'

if USE_SQLITE:
    # SQLite (Local Development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # PostgreSQL with Supabase (IPv4 forced at top of file)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': os.environ.get('DB_SSLMODE', 'require'),
                'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '10')),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Increased from default 8
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password Security Settings
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # Default (no external libs needed)
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Requires argon2-cffi
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',  # Requires bcrypt
]

# Password Reset Settings
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour (in seconds)


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =====================================================
# SUPABASE CONFIGURATION
# =====================================================
# Project: pulseofpeople (iwtgbseaoztjbnvworyq)
# Region: ap-south-1 (Mumbai)

# Supabase Project URL - used for REST API and Auth endpoints
SUPABASE_URL = os.environ.get('SUPABASE_URL', 'https://iwtgbseaoztjbnvworyq.supabase.co')

# Supabase Anonymous Key - public key for client-side auth (safe to expose)
SUPABASE_ANON_KEY = os.environ.get('SUPABASE_ANON_KEY', '')

# Supabase JWT Secret - CRITICAL: Used to validate JWT tokens from Supabase
# This is the actual secret key for JWT validation (NOT the anon key)
# Never expose this in frontend - backend only
SUPABASE_JWT_SECRET = os.environ.get('SUPABASE_JWT_SECRET', '')

# Supabase Service Role Key - Optional: For admin operations that bypass RLS
# Only use for trusted server-side operations (e.g., user provisioning)
SUPABASE_SERVICE_KEY = os.environ.get('SUPABASE_SERVICE_KEY', '')

# Validation: Ensure critical Supabase credentials are set
if not SUPABASE_JWT_SECRET and not DEBUG:
    raise ValueError(
        "SUPABASE_JWT_SECRET is required for production. "
        "Find it in Supabase Dashboard > Settings > API > JWT Settings"
    )

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.HybridAuthentication',  # Tries Supabase first, falls back to Django JWT
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # 24 hours (was 60 minutes)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # 30 days (was 7 days)
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# CORS Settings
# Parse and clean CORS origins, ensuring they have proper URL schemes
cors_origins_raw = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174'
).split(',')

CORS_ALLOWED_ORIGINS = []
for origin in cors_origins_raw:
    origin = origin.strip()  # Remove whitespace
    if origin:
        # Add scheme if missing
        if not origin.startswith(('http://', 'https://')):
            # Use https for Railway domains, http for localhost
            if 'railway.app' in origin or 'pulseofpeople.com' in origin:
                origin = f'https://{origin}'
            elif 'localhost' in origin or '127.0.0.1' in origin:
                origin = f'http://{origin}'
            else:
                origin = f'https://{origin}'
        CORS_ALLOWED_ORIGINS.append(origin)

# Always allow Railway frontend (for development/testing)
CORS_ALLOWED_ORIGINS.extend([
    'https://pulseofpeople-production.up.railway.app',
    'https://tvk.pulseofpeople.com',  # Custom frontend domain
])

# Production domains
if not DEBUG:
    CORS_ALLOWED_ORIGINS.extend([
        'https://pulseofpeople.com',
        'https://www.pulseofpeople.com',
        'https://api.pulseofpeople.com',
    ])

# Remove duplicates and print for debugging
CORS_ALLOWED_ORIGINS = list(set(CORS_ALLOWED_ORIGINS))
print(f"🔧 CORS_ALLOWED_ORIGINS configured: {CORS_ALLOWED_ORIGINS}")

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = False  # Explicitly set to False for security

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Additional CORS settings for reliability
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken', 'Authorization']

# Security Settings for Production
if not DEBUG:
    # Trust Railway's proxy headers for HTTPS detection
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Disable SSL redirect to avoid CORS preflight issues
    # Railway already handles HTTPS at the proxy level
    SECURE_SSL_REDIRECT = False

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CSRF trusted origins
csrf_origins_raw = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')

CSRF_TRUSTED_ORIGINS = []
for origin in csrf_origins_raw:
    origin = origin.strip()
    if origin:
        # Add scheme if missing
        if not origin.startswith(('http://', 'https://')):
            # Use https for Railway domains, http for localhost
            if 'railway.app' in origin or 'pulseofpeople.com' in origin:
                origin = f'https://{origin}'
            elif 'localhost' in origin or '127.0.0.1' in origin:
                origin = f'http://{origin}'
            else:
                origin = f'https://{origin}'
        CSRF_TRUSTED_ORIGINS.append(origin)

# Always trust custom frontend domain
CSRF_TRUSTED_ORIGINS.extend([
    'https://tvk.pulseofpeople.com',
    'https://pulseofpeople-production.up.railway.app',
])

if not DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'https://pulseofpeople.com',
        'https://www.pulseofpeople.com',
        'https://api.pulseofpeople.com',
    ])

# Remove duplicates
CSRF_TRUSTED_ORIGINS = list(set(CSRF_TRUSTED_ORIGINS))
print(f"🔧 CSRF_TRUSTED_ORIGINS configured: {CSRF_TRUSTED_ORIGINS}")

# Email Configuration
# For development, use console backend (prints emails to console)
# For production, configure SMTP settings
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@pulseofpeople.com')

# =====================================================
# CACHING CONFIGURATION (Redis)
# =====================================================

REDIS_URL = os.environ.get('REDIS_URL', None)

# Use Redis cache if available, otherwise fall back to local memory cache
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': 'pulseofpeople',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }
else:
    # Fall back to local memory cache for development without Redis
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'pulseofpeople-cache',
            'OPTIONS': {
                'MAX_ENTRIES': 1000
            }
        }
    }

# Cache time settings (in seconds)
CACHE_TTL = {
    'voter_stats': 300,  # 5 minutes
    'analytics_dashboard': 900,  # 15 minutes
    'sentiment_data': 600,  # 10 minutes
    'geographic_data': 3600,  # 1 hour
    'user_permissions': 1800,  # 30 minutes
    'constituency_list': 7200,  # 2 hours
}

# Session cache (using Redis)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# =====================================================
# MONITORING & ERROR TRACKING (Sentry)
# =====================================================

SENTRY_DSN = os.environ.get('SENTRY_DSN', '')

if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,  # 10% of transactions for performance monitoring
        send_default_pii=False,  # Don't send personally identifiable information
        environment=os.environ.get('ENVIRONMENT', 'production'),
        release=os.environ.get('APP_VERSION', '1.0.0'),
    )

# =====================================================
# STRUCTURED LOGGING
# =====================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
        'json': {
            'format': '{"time": "%(asctime)s", "level": "%(levelname)s", "module": "%(module)s", "message": "%(message)s"}',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'app.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'error.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api.authentication': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'api.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Create logs directory if it doesn't exist
import os
logs_dir = BASE_DIR / 'logs'
os.makedirs(logs_dir, exist_ok=True)

# =====================================================
# RATE LIMITING CONFIGURATION
# =====================================================

# Django-ratelimit uses cache backend
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_ENABLE = True  # Can be disabled for testing

# =====================================================
# FILE UPLOAD SECURITY
# =====================================================

# Maximum upload size (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Allowed file extensions
ALLOWED_UPLOAD_EXTENSIONS = [
    '.jpg', '.jpeg', '.png', '.gif',
    '.pdf', '.doc', '.docx', '.xls', '.xlsx', '.csv'
]

# =====================================================
# SECURITY ENHANCEMENTS
# =====================================================

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 hours

# CSRF Settings
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF for API
# CSRF_FAILURE_VIEW = 'api.views.csrf_failure'  # Commented out - view doesn't exist, using Django default

# Additional Security Headers (already in middleware, but configure here)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevent admin site from being indexed
SECURE_REFERRER_POLICY = 'same-origin'

# =====================================================
# API CONFIGURATION
# =====================================================

# API Version
API_VERSION = os.environ.get('API_VERSION', 'v1')

# Application Name
APP_NAME = os.environ.get('APP_NAME', 'Pulse of People')

# Pagination
REST_FRAMEWORK['PAGE_SIZE'] = 50
REST_FRAMEWORK['MAX_PAGE_SIZE'] = 500

# =====================================================
# TWO-FACTOR AUTHENTICATION
# =====================================================

# 2FA enforcement for roles
TWO_FACTOR_REQUIRED_ROLES = ['superadmin', 'admin', 'manager']

# OTP validity (in seconds)
OTP_VALIDITY = 30  # 30 seconds per code

# Backup codes
BACKUP_CODE_COUNT = 10

# =====================================================
# PERFORMANCE OPTIMIZATION
# =====================================================

# Database connection pooling
if not USE_SQLITE:
    DATABASES['default']['CONN_MAX_AGE'] = 600  # 10 minutes

# Disable Django's built-in atomic requests for better performance
# (Handle transactions explicitly in views when needed)
DATABASES['default']['ATOMIC_REQUESTS'] = False

# Template caching (production only)
if not DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]

# =====================================================
# ANALYTICS & MONITORING
# =====================================================

# Track slow queries (log queries taking longer than this)
SLOW_QUERY_THRESHOLD = 0.5  # 500ms

# Track API response times
TRACK_API_PERFORMANCE = True
