"""
PDF Report Generator using ReportLab
Generates professional PDF reports with branding, charts, and tables
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph,
    Spacer, PageBreak, Image, Frame, PageTemplate
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from io import BytesIO
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend


class ReportPDF:
    """PDF Report Generator"""

    def __init__(self, title, data, branding=None):
        self.title = title
        self.data = data
        self.branding = branding or {}
        self.buffer = BytesIO()
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Title'],
            fontSize=24,
            textColor=colors.HexColor('#1e3a8a'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))

        # Section heading
        self.styles.add(ParagraphStyle(
            name='SectionHeading',
            parent=self.styles['Heading1'],
            fontSize=16,
            textColor=colors.HexColor('#1e40af'),
            spaceBefore=20,
            spaceAfter=12,
        ))

        # Subsection heading
        self.styles.add(ParagraphStyle(
            name='SubsectionHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#3b82f6'),
            spaceBefore=12,
            spaceAfter=8,
        ))

        # Footer style
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.gray,
            alignment=TA_CENTER
        ))

    def add_cover_page(self, elements):
        """Add cover page with logo, title, and metadata"""
        # Logo (if provided)
        if self.branding.get('logo_path'):
            try:
                logo = Image(self.branding['logo_path'], width=2*inch, height=1*inch)
                elements.append(logo)
                elements.append(Spacer(1, 0.5*inch))
            except:
                pass

        # Title
        title = Paragraph(self.title, self.styles['CustomTitle'])
        elements.append(title)
        elements.append(Spacer(1, 0.3*inch))

        # Organization name
        if self.branding.get('organization_name'):
            org_name = Paragraph(
                self.branding['organization_name'],
                self.styles['Heading2']
            )
            elements.append(org_name)
            elements.append(Spacer(1, 0.2*inch))

        # Generated date
        date_text = f"Generated on: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
        date_para = Paragraph(date_text, self.styles['Normal'])
        elements.append(date_para)
        elements.append(Spacer(1, 0.1*inch))

        # Generated by
        if self.data.get('generated_by'):
            generated_by = Paragraph(
                f"Generated by: {self.data['generated_by']}",
                self.styles['Normal']
            )
            elements.append(generated_by)

        elements.append(Spacer(1, 0.5*inch))

        # Report period
        if self.data.get('date_from') and self.data.get('date_to'):
            period = Paragraph(
                f"<b>Report Period:</b> {self.data['date_from']} to {self.data['date_to']}",
                self.styles['Normal']
            )
            elements.append(period)

        elements.append(PageBreak())

    def add_executive_summary(self, elements):
        """Add executive summary section"""
        elements.append(Paragraph("Executive Summary", self.styles['SectionHeading']))
        elements.append(Spacer(1, 0.2*inch))

        # Key metrics in a table
        summary_data = self.data.get('summary', {})
        if summary_data:
            metrics_data = [
                ['Metric', 'Value'],
            ]

            for key, value in summary_data.items():
                metrics_data.append([
                    key.replace('_', ' ').title(),
                    str(value)
                ])

            metrics_table = Table(metrics_data, colWidths=[3*inch, 2*inch])
            metrics_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3b82f6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))

            elements.append(metrics_table)
            elements.append(Spacer(1, 0.3*inch))

        # Top insights
        insights = self.data.get('insights', [])
        if insights:
            elements.append(Paragraph("Top Insights", self.styles['SubsectionHeading']))
            for i, insight in enumerate(insights[:5], 1):
                bullet = Paragraph(f"{i}. {insight}", self.styles['Normal'])
                elements.append(bullet)
                elements.append(Spacer(1, 0.1*inch))

        elements.append(Spacer(1, 0.3*inch))

    def add_data_tables(self, elements):
        """Add data tables"""
        tables_data = self.data.get('tables', [])

        for table_info in tables_data:
            # Table title
            if table_info.get('title'):
                elements.append(Paragraph(table_info['title'], self.styles['SubsectionHeading']))
                elements.append(Spacer(1, 0.1*inch))

            # Table data
            table_data = table_info.get('data', [])
            if table_data:
                # Create table
                t = Table(table_data)
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3b82f6')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                    ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey])
                ]))

                elements.append(t)
                elements.append(Spacer(1, 0.3*inch))

    def add_charts(self, elements):
        """Add charts as images"""
        charts_data = self.data.get('charts', [])

        for chart_info in charts_data:
            # Chart title
            if chart_info.get('title'):
                elements.append(Paragraph(chart_info['title'], self.styles['SubsectionHeading']))
                elements.append(Spacer(1, 0.1*inch))

            # Generate chart image
            chart_type = chart_info.get('type', 'bar')
            chart_data = chart_info.get('data', {})

            chart_buffer = self._generate_chart(chart_type, chart_data)
            if chart_buffer:
                chart_img = Image(chart_buffer, width=5*inch, height=3*inch)
                elements.append(chart_img)
                elements.append(Spacer(1, 0.3*inch))

    def _generate_chart(self, chart_type, chart_data):
        """Generate matplotlib chart and return as image buffer"""
        try:
            fig, ax = plt.subplots(figsize=(10, 6))

            if chart_type == 'bar':
                labels = chart_data.get('labels', [])
                values = chart_data.get('values', [])
                ax.bar(labels, values, color='#3b82f6')
                ax.set_ylabel('Count')

            elif chart_type == 'line':
                x_data = chart_data.get('x', [])
                y_data = chart_data.get('y', [])
                ax.plot(x_data, y_data, marker='o', color='#3b82f6', linewidth=2)
                ax.set_xlabel(chart_data.get('x_label', 'X'))
                ax.set_ylabel(chart_data.get('y_label', 'Y'))
                ax.grid(True, alpha=0.3)

            elif chart_type == 'pie':
                labels = chart_data.get('labels', [])
                values = chart_data.get('values', [])
                ax.pie(values, labels=labels, autopct='%1.1f%%', startangle=90)

            plt.tight_layout()

            # Save to buffer
            buffer = BytesIO()
            plt.savefig(buffer, format='png', dpi=150, bbox_inches='tight')
            buffer.seek(0)
            plt.close(fig)

            return buffer
        except Exception as e:
            print(f"Error generating chart: {e}")
            return None

    def add_footer(self, canvas, doc):
        """Add page footer"""
        canvas.saveState()
        footer_text = f"Pulse of People - {datetime.now().strftime('%Y')} | Page {doc.page}"
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.gray)
        canvas.drawCentredString(
            letter[0] / 2,
            0.5 * inch,
            footer_text
        )
        canvas.restoreState()

    def generate(self):
        """Generate complete PDF report"""
        # Create document
        doc = SimpleDocTemplate(
            self.buffer,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=1*inch
        )

        # Build elements
        elements = []

        # Cover page
        self.add_cover_page(elements)

        # Executive summary
        if self.data.get('summary'):
            self.add_executive_summary(elements)

        # Charts
        if self.data.get('charts'):
            elements.append(Paragraph("Visualizations", self.styles['SectionHeading']))
            elements.append(Spacer(1, 0.2*inch))
            self.add_charts(elements)
            elements.append(PageBreak())

        # Data tables
        if self.data.get('tables'):
            elements.append(Paragraph("Detailed Data", self.styles['SectionHeading']))
            elements.append(Spacer(1, 0.2*inch))
            self.add_data_tables(elements)

        # Build PDF
        doc.build(elements, onFirstPage=self.add_footer, onLaterPages=self.add_footer)

        # Return buffer
        self.buffer.seek(0)
        return self.buffer


def generate_executive_summary_pdf(data, branding=None):
    """Generate executive summary PDF"""
    pdf = ReportPDF("Executive Summary Report", data, branding)
    return pdf.generate()


def generate_campaign_report_pdf(data, branding=None):
    """Generate campaign performance PDF"""
    pdf = ReportPDF("Campaign Performance Report", data, branding)
    return pdf.generate()


def generate_constituency_report_pdf(data, branding=None):
    """Generate constituency report PDF"""
    pdf = ReportPDF("Constituency Report", data, branding)
    return pdf.generate()
